### ISSUE TITLE
disk_usage fails on macOS/BSD with human=True

### ISSUE THREAD

**Issue by micahjsmith** [HDI-Project/mit-d3m#7]
* mit-d3m version: 0.1.2
* Python version: 3.6.9
* Operating System: Darwin-18.7.0-x86_64-i386-64bit

### Description

The disk_usage implementation relies on the external `du` command which has different options on BSD systems like macOS. I am confused why this would be implemented using external commands rather than native `shutil.disk_usage`.

### What I Did

```
>>> from mit_d3m.utils import disk_usage
>>> disk_usage('./README.md', human=True)
du: -h: No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/miniconda3/envs/autobazaar/lib/python3.6/site-packages/mit_d3m/utils.py", line 32, in disk_usage
    return subprocess.check_output(command).split()[0].decode('utf-8')
  File "/usr/local/miniconda3/envs/autobazaar/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/local/miniconda3/envs/autobazaar/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['du', '-s', './README.md', '-h']' returned non-zero exit status 1.
```

**Comment by micahjsmith** [comment]
Nevermind about shutil btw, I see that shutil.disk_usage is more like `df` rather than `du`.
